### ISSUE TITLE
Apply a linger timeout to small batches

### ISSUE THREAD

**Issue by dylanmei** [Nordstrom/kafka-connect-lambda#6]
When `aws.lambda.batch.enabled` is `true`, and the pending batch does not reach `maxBatchSizeBytes`, then the batch is not sent.

We should apply a linger timeout that ensures that small batches are sent, eventually. This value should be configurable, and have a reasonable default. For the configuration, support `ms` to be consistent with other properties in this connector.

**Comment by juanluispachecor** [comment]
One way of solving the issue is by adding a scheduled task that will flush records once a record has been sitting for a `linger.time.ms`. However, this creates synchronization issues, like:

- what if you try to add to the batch while the flushing is taking place?
- vice-versa, what if you flush while your batch is adding data?
- what happens with the exception that would get thrown in the thread that is flushing?

**Comment by dylanmei** [comment]
Kafka Connect has its own flush mechanism. We probably don't need this.

https://docs.confluent.io/current/connect/devguide.html#sink-tasks
> The `flush()` method is used during the offset commit process, which allows tasks to recover from failures and resume from a safe point such that no events will be missed. The method should push any outstanding data to the destination system and then block until the write has been acknowledged.
